-- PUNKT4-ACCOUNT-TYPE-FIX (2026-09-08, Michael): Die Live-RPC mappte
-- role='superadmin' hart auf membership_type 'team' → Michael Mathis,
-- 4VisionGlobal und Liga der Kreativen zeigten im MenschenAllModal das
-- falsche Label "Team" (Michael: "von wo du Team hast keine Ahnung").
-- Korrekte Kategorien-Logik (Michaels Vorgabe): Organisationen nach
-- org_type → Verein/Unternehmen/Projekt ("Einer für alle, alle Fair(ein)t"
-- = Projekt), Superadmins sind persoenliche Talent-Accounts → 'talent'.
-- 'team' als Ausgabewert entfaellt komplett. Basierend auf der LIVE-
-- Definition vom 2026-08-10 (Backup: backup_20260908i_rpc_discover_people_LIVE.sql.json).
CREATE OR REPLACE FUNCTION public.rpc_discover_people(p_search text DEFAULT NULL::text, p_sort text DEFAULT 'popular'::text, p_limit integer DEFAULT 20, p_offset integer DEFAULT 0)
 RETURNS TABLE(id uuid, full_name text, display_name text, username text, avatar_url text, bio text, location_label text, impact_eur numeric, followers_count integer, total_likes bigint, membership_type text)
 LANGUAGE sql
 STABLE SECURITY DEFINER
AS $function$ WITH base AS ( SELECT p.id, p.full_name, p.display_name, p.username, p.avatar_url, p.bio, p.location_label, p.impact_eur, CASE WHEN p.account_type = 'organization' AND p.org_type = 'verein' THEN 'verein' WHEN p.account_type = 'organization' AND p.org_type = 'unternehmen' THEN 'unternehmen' WHEN p.account_type = 'organization' THEN 'projekt' WHEN p.role = 'superadmin' THEN 'talent' WHEN p.role = 'talent' OR p.is_talent = true THEN 'talent' ELSE 'base' END AS membership_type, COALESCE((SELECT COUNT(*)::integer FROM public.follows f WHERE f.followed_id = p.id), 0) AS followers_count, p.created_at FROM public.profiles p WHERE (p.has_talent_profile = true OR p.is_member = true OR p.role = 'talent' OR p.role = 'wirker') AND COALESCE(p.focus_type, 'public') <> 'private' AND ( p_search IS NULL OR p_search = '' OR p.full_name ILIKE '%' || p_search || '%' OR p.display_name ILIKE '%' || p_search || '%' OR p.username ILIKE '%' || p_search || '%' OR p.bio ILIKE '%' || p_search || '%' ) ), scored AS ( SELECT b.*, COALESCE((SELECT COUNT(*) FROM public.post_reactions pr WHERE pr.type = 'inspire' AND ( (pr.post_type = 'work' AND EXISTS (SELECT 1 FROM public.works w WHERE w.id = pr.post_id AND w.user_id = b.id)) OR (pr.post_type = 'experience' AND EXISTS (SELECT 1 FROM public.experiences e WHERE e.id = pr.post_id AND e.user_id = b.id)) OR (pr.post_type = 'talent' AND EXISTS (SELECT 1 FROM public.talents ta WHERE ta.id = pr.post_id AND ta.user_id = b.id)) OR (pr.post_type IN ('moment','post') AND EXISTS (SELECT 1 FROM public.beitraege bt WHERE bt.id = pr.post_id AND bt.user_id = b.id)) OR (pr.post_type = 'impact' AND EXISTS (SELECT 1 FROM public.impact_applications ia WHERE ia.id = pr.post_id AND ia.user_id = b.id)) OR (pr.post_type = 'recommendation' AND EXISTS (SELECT 1 FROM public.recommendations rc WHERE rc.id = pr.post_id AND rc.from_user_id = b.id)) )), 0) AS total_likes FROM base b ) SELECT s.id, s.full_name, s.display_name, s.username, s.avatar_url, s.bio, s.location_label, s.impact_eur, s.followers_count, s.total_likes, s.membership_type FROM scored s ORDER BY CASE WHEN p_sort = 'followers' THEN s.followers_count END DESC NULLS LAST, CASE WHEN p_sort = 'likes' THEN s.total_likes END DESC NULLS LAST, CASE WHEN p_sort = 'alpha' THEN LOWER(COALESCE(s.full_name, s.display_name, s.username, '')) END ASC NULLS LAST, CASE WHEN p_sort = 'popular' OR p_sort IS NULL THEN (s.followers_count + s.total_likes) END DESC NULLS LAST, s.created_at DESC, s.id ASC LIMIT p_limit OFFSET p_offset; $function$

